CREATE
ALTER
DROP

--CRIAR NOVO BANCO DE DADOS
CREATE DATABASE NEWDATABASE;

--EXCLUI UM BANCO DE DADOS
DROP DATABASE NEWDATABASE;

--CRIAR TABELA
CREATE TABLE cliente(
    idcliente int,
    nome_cliente VarChar(100)
);

--ALTERA UMA TABELA
--ADICIONA NOVA COLUNA
--ALTERA O TIPO DE UMA COLUNA
ALTER TABLE cliente
ADD telefone varchar(11),
ALTER COLUMN nome_cliente TYPE varchar(110)


--EXCLUI UMA TABELA
DROP TABLE cliente;



